spring.application.name=security-practice
spring.security.user.name=user
spring.security.user.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/securitypractice
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# DEBUG
logging.level.org.springframework.security=DEBUG
# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

